# Checkmarx DAST

name: Dast-API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.pull_request.head.sha }}
    
    # Scan with Checkmarx DAST
    - name: run cxdast on my web app
      uses: checkmarx/dast-github-action@v1.0.2
      env: 
        CX_APIKEY: ${{ secrets.CXONE_APIKEY }}
      with:
        command: api
        config: ${{ github.event.pull_request.head.sha }}/dast-config/api.yaml
        environment_id: bea9d6ea-81b2-4212-a8f5-25ab1b890553
        openapi: ${{ github.event.pull_request.head.sha }}/swagger/openapi.yaml
        #project_id: 02013b5b-6837-40a5-8311-5f4779e82d71
        base_url: https://deu.ast.checkmarx.net/
        # fail_on: 'HIGH'
        verbose: true
        
