# Checkmarx DAST

name: Dast-API
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Scan with Checkmarx DAST
    - name: run cxdast on my API 
      uses: checkmarx/dast-github-action@v1.0.2
      env: 
        CX_APIKEY: ${{ secrets.CXONE_CANARY_APIKEY }}
      with:
        command: api
        config: ./dast-config/api.yaml
        environment_id: 0953b49c-8a5b-4628-8302-ce0c1127264a
        openapi: ./swagger/openapi.yaml
        #project_id: 02013b5b-6837-40a5-8311-5f4779e82d71
        base_url: https://eu.ast.checkmarx.net/
        # fail_on: 'HIGH'
        verbose: true
        output: ./output
    - name: Reclaim output directory
      if: always()  
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v3
      if: always()
      name: Attach DAST report as an artifact to workflow  
      with:
        name: report
        path: ./output        
