# Checkmarx DAST

name: Dast-web
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    

    # Scan with Checkmarx DAST
    - name: run cxdast on my web app
      uses: checkmarx/dast-github-action@v1.0.2
      env: 
        CX_APIKEY: ${{ secrets.CXONE_CANARY_APIKEY }}
      with:
        command: web
        config: ./dast-config/web.yaml
        environment_id: dc5dad24-9652-4486-81fd-8ff89610d523
        base_url: https://eu.ast.checkmarx.net/
        # fail_on: 'HIGH'
        verbose: true
        output: ./output
    - name: Reclaim output directory
      if: always()  
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v3
      if: always()
      name: Attach DAST report as an artifact to workflow  
      with:
        name: report
        path: ./output        
