# Checkmarx DAST

name: Dast-web
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan with Checkmarx DAST
    - name: run cxdast on my web app
      uses: checkmarx/dast-github-action@v1.0.2
      env: 
        CX_APIKEY: ${{ secrets.CXONE_CANARY_APIKEY }}
      with:
        command: "web"
        config: './dast-config/web.yaml'
        base_url: "https://deu.ast.checkmarx.net"
        environment_id: "2f776f4a-dfda-46d1-9fda-b879307d9b76"
        fail_on: "HIGH"
        verbose: true
        output: ./output
