# Checkmarx DAST

name: Dast-API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Scan with Checkmarx DAST
    - name: run cxdast on my web app
      uses: checkmarx/dast-github-action@v1.0.2
      env: 
        CX_APIKEY: ${{ secrets.CXONE_APIKEY }}
      with:
        command: api
        config: ./dast-config/api.yaml
        environment_id: "2f776f4a-dfda-46d1-9fda-b879307d9b76"
        openapi: ./swagger/openapi.yaml
        #project_id: 02013b5b-6837-40a5-8311-5f4779e82d71
        base_url: https://deu.ast.checkmarx.net/
        # fail_on: 'HIGH'
        verbose: true
        output: ./output
    - name: Reclaim output directory  
      if: always()  
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v3
      if: always()
      name: Upload Logs
      with:
        name: report
        path: ./output        
